### ISSUE TITLE
Make a prototype first

### ISSUE THREAD

**Issue by PladsElsker** [Ozu-Beatmap-Toolset/ozu-gui#6]
We want the following features:

- ugly static placement area;
- place circles and export them in an osu file;
- place sliders and export them in an osu file;
- place spinners and export them in an osu file;
- every single hitobject has no color or number on it, it's an imported image;
- use the scroll wheel to move forward/backward in time;
- press space to play the pattern;
- ctrl + scroll wheel to change time divisions on measure bar;
- add a measure bar display that you can interact with to go to certain positions in time. 

That's it. That's already very hard to do, let's start with this. 

DON'T IMPLEMENT YET
- song player;
- metadata or difficulty settings (they shall be hardcoded for now);
- bg image selection;
- importing beatmaps in general.

**Comment by John-WL** [comment]
Alright, right now we can add circles by left-clicking on the playfield, and we have shortcut events that are ready to be implemented.

We need to figure out how to progressively show/hide hitobjects that we added in the DOM to play the beatmap.

**Comment by John-WL** [comment]
yeay! it works.

One problem we have if we want to reuse this architecture is that the circles are placed and memorized relative to the UI, and not to the playfield area. 
As things stand right now, if we handle the scaling of the window by just moving the hitobjects relative to the new field position and scale, we might end up with drift building up overtime, which I would like to avoid. 
Therefore, we need to store the position of hitobjects to recalculate their positions according to an unchanging position.

**Comment by John-WL** [comment]
just to sum up our original plan:
- ~~ugly static placement area;~~
- place circles and export them in an osu file;
- place sliders and export them in an osu file;
- place spinners and export them in an osu file;
- ~~every single hitobject has no color or number on it, it's an imported image;~~
- ~~use the scroll wheel to move forward/backward in time;~~
- ~~press space to play the pattern;~~
- ~~ctrl + scroll wheel to change time divisions on measure bar;~~
- add a measure bar display that you can interact with to go to certain positions in time.

We can place circles right now, but not export them in an osu file.

**Comment by John-WL** [comment]
When you think about it...
Aren't circles actually bezier curves of degree 0?
And aren't linear sliders actually bezier curves of degree 1?

Should we implement every possible hitobject as bezier curves?

**Comment by John-WL** [comment]
for displaying sliders???
https://stackoverflow.com/questions/49900770/overlapped-elements-with-opacity-and-handling-the-hover-on-those
